src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java
src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java

fixes bug in TypeUtils.equals(WildcardType, Type) where it was incorrectly returning true when the second argument was not a Wildcard type.

#LAN-1114 fixes bug in TypeUtils.equals(WildcardType, Type)

---

src/main/java/org/apache/commons/lang3/ThreadUtils.java
src/test/java/org/apache/commons/lang3/ThreadUtilsTest.java

Add org.apache.commons.lang3.ThreadUtils which provide helper methods related to java.lang.Thread (2nd PR)
This PR replaces https://github.com/apache/commons-lang/pull/61
ThreadUtils class exposes the following static methods:
findThreadById(long)
findThreadById(long, String)
findThreadById(long, ThreadGroup)
findThreadGroups(ThreadGroup, boolean, ThreadGroupPredicate)
findThreadGroups(ThreadGroupPredicate)
findThreadGroupsByName(String)
findThreads(ThreadGroup, boolean, ThreadPredicate)
findThreads(ThreadPredicate)
findThreadsByName(String)
findThreadsByName(String, String)
findThreadsByName(String, ThreadGroup)
getAllThreadGroups()
getAllThreads()
getSystemThreadGroup()

Add ThreadUtils (2nd PR)

---

src/main/java/org/apache/commons/lang3/StringUtils.java

deprecated ObjectUtils.toString(Object) method (which is o.k. to use as
long as commons-lang3 does not require java 7 or greater)

@SuppressWarnings("deprecation") to joinWith, because it uses the

---

src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
src/test/java/org/apache/commons/lang3/builder/ReflectionToStringBuilderTest.java
src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java

As described in it's [javadoc](http://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/builder/ReflectionToStringBuilder.html#ReflectionToStringBuilder(java.lang.Object)), ReflectionToStringBuilder constructor will throw IllegalArgumentException if the Object to build a toStringfor is null, while in fact it won't.
I had create the Issue [LANG-1132](https://issues.apache.org/jira/browse/LANG-1132) for this.

ReflectionToStringBuilder doesn't throw IllegalArgumentException when the constructor's object param is null

---

src/main/java/org/apache/commons/lang3/time/DateUtils.java
src/main/java/org/apache/commons/lang3/time/FastDateParser.java
src/test/java/org/apache/commons/lang3/time/FastDateFormatTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParserSDFTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParserTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParser_MoreOrLessTest.java

use hashmap for performance
break down regular expressions to per-format, allowing
ParsePosition to get set
add parse with Calendar input, allowing client to set leniency
and/or replace display names

refactor FastDateParser

---

src/main/java/org/apache/commons/lang3/StringUtils.java

as suggested by Larry West in https://issues.apache.org/jira/browse/LANG-1182

LANG-1182: adding clarifying examples to StringUtils#containsAny javadoc

---

src/main/java/org/apache/commons/lang3/time/FastDateParser.java
src/test/java/org/apache/commons/lang3/time/FastDateParser_TimeZoneStrategyTest.java

Java 8u60 has a change where `DateFormatSymbols.getZoneStrings` returns arrays with 7 elements instead of 5 like it previously had. For some locales, the additional two elements are null.
Example from the unit tests:
```
Running org.apache.commons.lang3.time.FastDateParser_TimeZoneStrategyTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.597 sec <<< FAILURE! - in org.apache.commons.lang3.time.FastDateParser_TimeZoneStrategyTest
testTimeZoneStrategyPattern(org.apache.commons.lang3.time.FastDateParser_TimeZoneStrategyTest)  Time elapsed: 0.597 sec  <<< ERROR!
java.lang.NullPointerException: null
at org.apache.commons.lang3.time.FastDateParser$TimeZoneStrategy.<init>(FastDateParser.java:856)
at org.apache.commons.lang3.time.FastDateParser.getLocaleSpecificStrategy(FastDat …
```

LANG-1186 Fix NullPointerException in FastDateParser$TimeZoneStrategy

---

src/main/java/org/apache/commons/lang3/text/StrSubstitutor.java
src/test/java/org/apache/commons/lang3/text/StrSubstitutorTest.java

StrSubstitutor can now optionally preserve the escape character for an
escaped reference, which is useful when substitution takes place in
multiple phases and some references are intentionally unresolved.  Prior
to this change, an unresolved reference `${a}` and an escaped reference
`$${a}` may result in the same string `${a}`, making it impossible for
an additional substitution phase to distinguish between escaped
references and non-escaped references.

StrSubstitutor can preserve escapes

---

src/main/java/org/apache/commons/lang3/JavaVersion.java
src/main/java/org/apache/commons/lang3/SystemUtils.java
src/test/java/org/apache/commons/lang3/JavaVersionTest.java
src/test/java/org/apache/commons/lang3/SystemUtilsTest.java

Not complete: `JavaVersion` expects the `java.version` system property to return `1.x` but for java 9 it will return `9*`. Not sure how to handle this.

LANG-1197: Prepare Java 9 detection

---

src/main/java/org/apache/commons/lang3/time/DateUtils.java
src/test/java/org/apache/commons/lang3/time/DateUtilsTest.java

Added new toCalendar method in DateUtils with 4 unit tests as proposed in LANG-1255.
Link: https://issues.apache.org/jira/browse/LANG-1255

Lang 1255: Add DateUtils.toCalendar(Date, TimeZone) and 4 unit tests

---

src/main/java/org/apache/commons/lang3/Conversion.java
src/main/java/org/apache/commons/lang3/SerializationUtils.java
src/main/java/org/apache/commons/lang3/concurrent/ConcurrentRuntimeException.java
src/main/java/org/apache/commons/lang3/concurrent/package-info.java
src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java
src/main/java/org/apache/commons/lang3/text/StrSubstitutor.java
src/main/java/org/apache/commons/lang3/text/translate/NumericEntityUnescaper.java
src/test/java/org/apache/commons/lang3/CharUtilsPerfRun.java
src/test/java/org/apache/commons/lang3/LocaleUtilsTest.java
src/test/java/org/apache/commons/lang3/ObjectUtilsTest.java
src/test/java/org/apache/commons/lang3/SystemUtilsTest.java
src/test/java/org/apache/commons/lang3/concurrent/ThresholdCircuitBreakerTest.java
src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java
src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java
src/test/java/org/apache/commons/lang3/text/StrLookupTest.java
src/test/java/org/apache/commons/lang3/text/StrSubstitutorTest.java
src/test/java/org/apache/commons/lang3/time/DateFormatUtilsTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParserSDFTest.java

fix typos in several local variables.
Please, look closely at changes in those files:
- org/apache/commons/lang3/text/StrSubstitutorTest.java ([Anchor](https://github.com/apache/commons-lang/compare/master...Abrasha:fix/non-critical-typos?expand=1#diff-8b41a3f8f69fbfc88251e619307f01ff))
- org/apache/commons/lang3/exception/ExceptionUtils.java ([Anchor](https://github.com/apache/commons-lang/compare/master...Abrasha:fix/non-critical-typos?expand=1#diff-40d839797a9b13ac5aa8d881e7e9f2d6))

Fix non-critical typos in comments and JavaDoc

---

src/test/java/org/apache/commons/lang3/ObjectUtilsTest.java

This patch employs Java 7's syntax to catch multiple exceptions in
the same block with the `|` operator to make `ObjectUtilsTest`'s code
cleaner and easier to read.

ObjectUtilsTest: collapse empty catch blocks

---

src/main/java/org/apache/commons/lang3/text/StrSubstitutor.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

This change adds the missing `s` character to complete the `[a-z]` namespace.
Since the commit only affects Javadoc and test code, I refrained from creating a Jira issue. If I should create one, please leave a comment.
I have signed the ICLA via email.
Signed-off-by: Tobias Gesellchen <tobias@gesellix.de>

(doc) Use the full alphabet for the well-known example text.

---

pom.xml
src/changes/changes.xml
src/main/java/org/apache/commons/lang3/CharSequenceUtils.java
src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsEqualsIndexOfTest.java

@MarkDacek - let me know what you think.
This extends #251.

LANG-1300: Added documentation

---

src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
src/test/java/org/apache/commons/lang3/builder/ReflectionToStringBuilderExcludeNullValuesTest.java

@chtompki 
First attempt at this. In order to avoid a large refactor or breaking existing implementations, the boolean has to be a negative (isExcludeNullValues instead of appendNullValues).

LANG-1167: Add null filter to ReflectionToStringBuilder

---

src/changes/changes.xml
src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java

See https://issues.apache.org/jira/browse/LANG-1337 for issue description and explanation of the changes here.
In summary, we specify the ArrayList's initial capacity, this way the String built through reflection has the expected value. Tested with Oracle JDK 7 and 8, and IBM JDK 8.

LANG-1337: Fix test failures in IBM JDK 8 for ToStringBuilderTest by specifying the ArrayList initial capacity.

---

pom.xml
src/changes/changes.xml

This change duplicates the maven-jar-plugin configuration from parent
pom. After we have implemented a solution for this in parent pom, this
commit should be reverted.

LANG-1338: Add Automatic-Module-Name MANIFEST entry for Java 9 compatibility.

---

src/main/java/org/apache/commons/lang3/ObjectUtils.java

Commit 6ea2fc8 inadvertently introduced trailing white spaces in `ObjectUtils`' code, thus breaking the Checkstyle validation.
This patch removes these redundant TWS in order to allow the build to pass.

Remove ObjectUtils' trailing white spaces

---

src/main/java/org/apache/commons/lang3/ArrayUtils.java
src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java

@chtompki 
If this is deemed worthy or needs improvement - let me know.

LANG-1402: Null/index safe get methods for ArrayUtils

---

.travis.yml

Remove the allow_failures section for Java 11.

Looks like Java 11 no longer fails the build

---

src/test/java/org/apache/commons/lang3/ValidateTest.java

Proposal for a better structure of tests using `@Nested`. Each method should have it's own `@Nested` container which is called like the method. Inside that container each overload has it's own `@Nested` container. I did this for `Validate.isTrue` to show the approach.

Convert tests for Validate.isTrue overloads to @Nested test

---

src/test/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/BasicThreadFactoryTest.java
src/test/java/org/apache/commons/lang3/concurrent/CallableBackgroundInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/CircuitBreakingExceptionTest.java
src/test/java/org/apache/commons/lang3/concurrent/ConcurrentUtilsTest.java
src/test/java/org/apache/commons/lang3/concurrent/ConstantInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/EventCountCircuitBreakerTest.java
src/test/java/org/apache/commons/lang3/concurrent/LazyInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/MemoizerTest.java
src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/ThresholdCircuitBreakerTest.java
src/test/java/org/apache/commons/lang3/concurrent/TimedSemaphoreTest.java

Upgrade the tests in the concurrent package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
Unlike `org.junit.Test`, `org.junit.jupiter.api.Test` does not have an `expected` argument. Instead, an explicit call to `org.junit.jupiter.api.Assertions.assertThrows` is used. This call allows the test to pinpoint the exact statement that is expected to throw the exception and allows making the tests a bit stricter by preventing
false-positives that could occur if the setup code would throw the expected exception instead of the statement that was supposed to throw it.
Another notable change was performed in `MemoizerTest`. …

Update concurrent tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/event/EventListenerSupportTest.java
src/test/java/org/apache/commons/lang3/event/EventUtilsTest.java

Upgrade the tests in the event package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
While most of these changes are drop-in replacements with no functional benefit, it is worth noting the tests that test thrown exceptions.
Prior to this patch, this package tested for exceptions in two ways, neither of which are supported in JUnit Jupiter:
1. With the `expected` argument of the `org.junit.Test` annotation.
2. With the `org.junit.rules.ExpectedException` `@Rule`
Both of these usages were replaced with calls to `org.junit.jupiter.api.Assertions#assertThrows`.

Update event tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/exception/AbstractExceptionContextTest.java
src/test/java/org/apache/commons/lang3/exception/CloneFailedExceptionTest.java
src/test/java/org/apache/commons/lang3/exception/ContextedExceptionTest.java
src/test/java/org/apache/commons/lang3/exception/ContextedRuntimeExceptionTest.java
src/test/java/org/apache/commons/lang3/exception/DefaultExceptionContextTest.java
src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java

Upgrade the tests in the `exception` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
Another non-obvious change was performed in `ContextedRuntimeExceptionTest`. Unlike JUnit Vintage's `@Before`, JUnit Jupiter's `@BeforeEach` does not apply if a parent's method is annotated with it and the overriding method is not, so an explicit `@BeforeEach` annotation had to be added to `ContexedTuntimeExceptionTest#setUp()`.
It's also worth …

Update exception tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/reflect/ConstructorUtilsTest.java
src/test/java/org/apache/commons/lang3/reflect/FieldUtilsTest.java
src/test/java/org/apache/commons/lang3/reflect/InheritanceUtilsTest.java
src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java
src/test/java/org/apache/commons/lang3/reflect/TypeLiteralTest.java
src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java

Upgrade the tests in the `reflect` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
Unlike `org.junit.Assume`, `org.junit.jupiter.api.Assumptions` does not have an `assumeNotNull` method. Instead, `assumeTrue` was used with an explicit condition of a variable being different than `null`.
It's also worth noting this is a minimal patch for migrating the package's tests to Jupiter. There are several tests that can be made more elegant …

Update reflect tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/text/CompositeFormatTest.java
src/test/java/org/apache/commons/lang3/text/ExtendedMessageFormatTest.java
src/test/java/org/apache/commons/lang3/text/FormattableUtilsTest.java
src/test/java/org/apache/commons/lang3/text/StrBuilderAppendInsertTest.java
src/test/java/org/apache/commons/lang3/text/StrBuilderTest.java
src/test/java/org/apache/commons/lang3/text/StrLookupTest.java
src/test/java/org/apache/commons/lang3/text/StrMatcherTest.java
src/test/java/org/apache/commons/lang3/text/StrSubstitutorTest.java
src/test/java/org/apache/commons/lang3/text/StrTokenizerTest.java
src/test/java/org/apache/commons/lang3/text/WordUtilsTest.java
src/test/java/org/apache/commons/lang3/text/translate/EntityArraysTest.java
src/test/java/org/apache/commons/lang3/text/translate/LookupTranslatorTest.java
src/test/java/org/apache/commons/lang3/text/translate/NumericEntityEscaperTest.java
src/test/java/org/apache/commons/lang3/text/translate/NumericEntityUnescaperTest.java
src/test/java/org/apache/commons/lang3/text/translate/OctalUnescaperTest.java
src/test/java/org/apache/commons/lang3/text/translate/UnicodeEscaperTest.java
src/test/java/org/apache/commons/lang3/text/translate/UnicodeUnescaperTest.java
src/test/java/org/apache/commons/lang3/text/translate/UnicodeUnpairedSurrogateRemoverTest.java

Upgrade the tests in the `text` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
It's also worth noting this is a minimal patch for migrating the package's tests to Jupiter. There are several tests that can be made more elegant with Jupiter's new features, but that work is left for subsequent patches.

Update text tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/tuple/ImmutablePairTest.java
src/test/java/org/apache/commons/lang3/tuple/ImmutableTripleTest.java
src/test/java/org/apache/commons/lang3/tuple/MutablePairTest.java
src/test/java/org/apache/commons/lang3/tuple/MutableTripleTest.java
src/test/java/org/apache/commons/lang3/tuple/PairTest.java
src/test/java/org/apache/commons/lang3/tuple/TripleTest.java

Upgrade the tests in the text package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.

Update tuple tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/math/FractionTest.java
src/test/java/org/apache/commons/lang3/math/IEEE754rUtilsTest.java
src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java

Upgrade the tests in the `math` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
Unlike `org.junit.Assert.assertEquals(double, double, double)`, `org.junit.jupiter.api.Assertions.assertEquals(double, double, double)` does not support deltas of zero, only strictly positive deltas. This issue will be addressed in JUnit Jupiter 5.4 (see https://github.com/junit-team/junit5/pull/1613 for details). In the meanwhile, …

Update math tests to JUnit Jupiter

---

src/test/java/org/apache/commons/lang3/mutable/MutableBooleanTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableByteTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableDoubleTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableFloatTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableIntTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableLongTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableObjectTest.java
src/test/java/org/apache/commons/lang3/mutable/MutableShortTest.java

Upgrade the tests in the `mutable` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
Unlike `org.junit.Assert.assertEquals(double, double, double)`, `org.junit.jupiter.api.Assertions.assertEquals(double, double, double)` does not support deltas of zero, only strictly positive deltas.
This issue will be addressed in JUnit Jupiter 5.4 (see https://github.com/junit-team/junit5/pull/1613 for details). In the meanwhile, …

Update mutable tests to JUnit Jupiter

---

pom.xml
src/test/java/org/apache/commons/lang3/time/DateFormatUtilsTest.java
src/test/java/org/apache/commons/lang3/time/DateUtilsFragmentTest.java
src/test/java/org/apache/commons/lang3/time/DateUtilsRoundingTest.java
src/test/java/org/apache/commons/lang3/time/DateUtilsTest.java
src/test/java/org/apache/commons/lang3/time/DurationFormatUtilsTest.java
src/test/java/org/apache/commons/lang3/time/FastDateFormatTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParserSDFTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParserTest.java
src/test/java/org/apache/commons/lang3/time/FastDateParser_MoreOrLessTest.java
src/test/java/org/apache/commons/lang3/time/FastDatePrinterTest.java
src/test/java/org/apache/commons/lang3/time/FastDatePrinterTimeZonesTest.java
src/test/java/org/apache/commons/lang3/time/FastTimeZoneTest.java
src/test/java/org/apache/commons/lang3/time/GmtTimeZoneTest.java
src/test/java/org/apache/commons/lang3/time/StopWatchTest.java
src/test/java/org/apache/commons/lang3/time/WeekYearTest.java

Upgrade the tests in the `time` package to use JUnit Jupiter as part of the effort to remove the dependency on the Vintage Engine.
JUnit Jupiter no longer has a concept of runners. Tests previously run with the `org.junit.runners.Parameterized` runner were rewritten to use `@ParameterizedTest` and a `@MethodSource`.
JUnit Jupiter also no longer has the concept of Rules. Usages of the `SystemDefaultsSwitch` rule and its accompanying annotates were replaced with the `@DefaultLocale` …

Update time tests to JUnit Jupiter

---

src/changes/changes.xml
src/main/java/org/apache/commons/lang3/StringUtils.java

Implement the same edge case logic for null. Use the same parameter
names. Use the same Javadoc wording. Change the equals method to use a
step-wise charAt comparison.

Consolidate the StringUtils.equals and equalsIgnoreCase methods.

---

src/main/java/org/apache/commons/lang3/StringUtils.java

While I was in the neighbourhood for #411 , I noticed the javadocs for the `startIndex` parameter in the `StringUtils.join()` methods says "it is an error to pass in an **end** index past the end of the array".

(doc) Fix javadoc for 'startIndex' parameter of StringUtils.join() methods

---

src/main/java/org/apache/commons/lang3/JavaVersion.java

When nom is null, return directly without unnecessary judgment.

Improvement JavaVersion get method

---

src/main/java/org/apache/commons/lang3/Functions.java
src/test/java/org/apache/commons/lang3/FunctionsTest.java

I think some changes slipped with some recent change. Reviewing PR of contributors, it was quite hard to distinguish what was failing due to the contributor's PR.
If Travis is happy with this change, will merge it as I think this is a small change (formatting, adding javadocs, commas, replacing tab characters, etc).
Cheers
Bruno

Fix checkstyle violations (tabs, missing spaces after commas, missing javadocs)

---

src/main/java/org/apache/commons/lang3/builder/DiffResult.java
src/test/java/org/apache/commons/lang3/builder/DiffResultTest.java

As explained in the [JIRA ticket](https://issues.apache.org/jira/browse/LANG-1485) I add a getter for the `lhs` and `rhs` objects of the `DiffResult`
Tests included

LANG-1485 : Add getters for lhs and rhs objects in DiffResult

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

[LANG-1489] Add null-safe APIs as StringUtils.toRootLowerCase(String) and StringUtils.toRootUpperCase(String)
https://issues.apache.org/jira/browse/LANG-1489

[LANG-1489] Add null-safe APIs as StringUtils.toRoot[Lower|Upper]Case(String)

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

Fixed documentation. No tests added because existings unit tests seam to cover these code examples reasonably well.

[LANG-1426] Corrected usage examples in Javadocs

---

src/main/java/org/apache/commons/lang3/Functions.java
src/test/java/org/apache/commons/lang3/FunctionsTest.java

The Functions class implemented the `asXXX` methods in a "copy-paste" way instead of using the already implemented static methods of the same class.
Also the tests for the methods `asPredicate` and `asBiPredicate` were missing.

Code refactor to simplify Functions and new tests

---

src/main/java/org/apache/commons/lang3/EnumUtils.java
src/test/java/org/apache/commons/lang3/EnumUtilsTest.java

Add Overloading Methods getEnum and getEnumIgnoreCase To EnumUtils

LANG-1495 Update EnumUtils.java

---

src/main/java/org/apache/commons/lang3/builder/HashCodeBuilder.java
src/test/java/org/apache/commons/lang3/builder/HashCodeBuilderTest.java

this fixes [LANG-1500](https://issues.apache.org/jira/projects/LANG/issues/LANG-1500).
In this PR, it proposes:
* Sort the fields with their names for a deterministic order (alphabetical)
* Modify some test assertions to match the behavior

LANG-1500 | Test may fail due to a different order of fields returned by reflection api

---

src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
src/test/java/org/apache/commons/lang3/builder/MultilineRecursiveToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/RecursiveToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java

This fixes [LANG-1501](https://issues.apache.org/jira/projects/LANG/issues/LANG-1501?filter=allissues).
In this PR, it proposes:
* Sort the fields with their names for a deterministic order (alphabetical)
* Modify some test assertions to match the behavior

[LANG-1501] Sort fields in ReflectionToStringBuilder for deterministic order

---

src/main/java/org/apache/commons/lang3/Functions.java

are already defined and still the implementation itself does not use them in the same file. It makes the code shorter and simpler.

Reuse own code in Functions.java

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

Now `StringUtils#wrapIfMissing(String, char)` and `StringUtils#wrapIfMissing(String, String)` does not allocate buffer when input is already wrapped.
Here are the benchmark results on my machine:
```
Benchmark                    (input)   Mode  Samples    Score  Score error   Units
optimized    /should not be wrapped/  thrpt       20  357.849        4.525  ops/us
optimized          should be wrapped  thrpt       20   33.779        0.246  ops/us
original     /should not be wrapped/  thrpt       20   35.581        0.236  ops/us
original           should be wrapped  thrpt       20   33.671        0.360  ops/us
```

LANG-1523: Avoid unnecessary allocation in StringUtils.wrapIfMissing.

---

src/main/java/org/apache/commons/lang3/BooleanUtils.java
src/test/java/org/apache/commons/lang3/BooleanUtilsTest.java

I stubmled over this during the week and am wondering why 1 and 0 are not a default true and false representation. So I created this PR. I'm not strongly opnionated about it. So if there is a good reason for 1 and 0 not beeing a good case here, feel free to close it.
I think, parsing the string to an int before calling toBoolean is unnecessary. And it should be common enough that you shouldn't have to call: toBooleanObject(final String str, final String trueString, final String falseString, final String nullString)

 Added 1 and 0 in toBooleanObject(final String str) 

---

src/main/java/org/apache/commons/lang3/CharUtils.java
src/main/java/org/apache/commons/lang3/SerializationUtils.java
src/main/java/org/apache/commons/lang3/builder/DiffBuilder.java
src/main/java/org/apache/commons/lang3/builder/DiffResult.java
src/main/java/org/apache/commons/lang3/math/Fraction.java
src/main/java/org/apache/commons/lang3/math/IEEE754rUtils.java
src/main/java/org/apache/commons/lang3/reflect/FieldUtils.java
src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java
src/main/java/org/apache/commons/lang3/time/DateUtils.java
src/main/java/org/apache/commons/lang3/time/FormatCache.java
src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java

The Javadocs of some methods that use the `Validate.notNull()` method incorrectly refer to `IllegalArgumentException` instead of `NullPointerException` as the exception thrown when a value is `null`, while the methods' tests check for `NullPointerException`. In addition, some of said methods use `Validate.isTrue()` instead of `Validate.notNull()` for null checking.
This PR fixes both issues as they are closely related.

Correct Javadocs of methods that use Validate.notNull() and replace some uses of Validate.isTrue() with Validate.notNull().

---

src/main/java/org/apache/commons/lang3/math/NumberUtils.java

Remove redundant parameter:str.length() as by default substring(int beginIndex) method returns the substring from the specified index and extends till string length. 
And as str.length() is final.So, storing str.length() into a variable final int length = str.length() to avoid calling function str.length() sevaral times.

Remove redudant argument from substring call

---

src/changes/changes.xml
src/main/java/org/apache/commons/lang3/RandomUtils.java
src/test/java/org/apache/commons/lang3/RandomUtilsTest.java

The method has been changed to use exclusively the long datatype to
generate the value.
The implementation is taken from the Commons RNG project.

[LANG-1592] Correct implementation of RandomUtils.nextLong(long, long)

---

src/main/java/org/apache/commons/lang3/ArrayUtils.java
src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java

- Add support for the missing types to toPrimitive(Object)
- Added tests for toPrimitive methods which did not have test coverage yet
- Added explicit test for the toPrimitive(Object) method for all primitive types

[LANG-1596] ArrayUtils.toPrimitive(Object) does not support boolean and other types

---

src/main/java/org/apache/commons/lang3/builder/ToStringStyle.java
src/test/java/org/apache/commons/lang3/builder/DefaultToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/MultiLineToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/NoClassNameToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/NoFieldNamesToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/ShortPrefixToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/SimpleToStringStyleTest.java
src/test/java/org/apache/commons/lang3/builder/StandardToStringStyleTest.java

Restore non-json-style handling of appendDetail() for Collection
* addresses issue introduced in LANG-1542 with commit 1dddec8
* add test cases for non-empty collections, maps, and arrays
* break out those test cases into separate methods for legibility
CLA: n/a, covered by clause 5 of the Apache License

[LANG-1600] Restore handling of collections for non-JSON ToStringStyle

---

pom.xml

Alternatively, we can rollback to `org.junit.jupiter:junit-jupiter:5.6.2`.

[LANG-1608] Include junit-bom for dependency version alignment.

---

src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java

Some of the tests related to finding min and max values does not have types declared. As a result min/max of value ```int``` methods are being tested multiple times without invoking target methods ```byte```, ```long``` etc.
I fixed types and added casting where required.

NumberUtilsTest - incorrect types in min/max tests

---

src/main/java/org/apache/commons/lang3/SystemUtils.java

the javadoc for isJavaVersionAtMost was the same as for isJavaVersionAtLeast! They sure don't do the same thing :)

fix javadoc for isJavaVersionAtMost

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

When wrapToken.length() * 2 is larger than str.length(), and str starts with and ends with wrapToken, the function calls str.substring(beginIndex, endIndex) with beginIndex larger than endIndex, which throws a StringIndexOutOfBoundsException.
It should return the original string since it is not quoted properly with the wrapToken according to documentation.

LANG-1610: Fix StringUtils.unwrap throws StringIndexOutOfBoundsException

---

src/main/java/org/apache/commons/lang3/BooleanUtils.java
src/main/java/org/apache/commons/lang3/StringUtils.java

Corrected:
StringUtils.isNumericSpace incorrectly refer to isNumeric
BooleanUtils.toBoolean incorrectly refer to toBooleanObject

[LANG-1622] Corrected reference to right methods.

---

src/main/java/org/apache/commons/lang3/BooleanUtils.java

One more function is referred incorrectly in BooleanUtils i.e. toBooleanObject(final Integer value).

[LANG-1622] Javadoc of BooleanUtils incorrectly refers to another method

---

src/main/java/org/apache/commons/lang3/StringUtils.java

Avoid extra computations by getting the string size only once. 
https://issues.apache.org/jira/browse/LANG-1620

[LANG-1620] - refine StringUtils.lastIndexOfIgnoreCase

---

src/main/java/org/apache/commons/lang3/StringUtils.java

Avoid extra computations by getting the string size only once.
https://issues.apache.org/jira/browse/LANG-1619

[LANG-1619] - refine StringUtils.abbreviate

---

src/main/java/org/apache/commons/lang3/text/ExtendedMessageFormat.java

Use `<code>{</code>` instead of `{@code {}`, as the latter one is
invalid. It works in the current javadoc, as it is accompanied
with the equally invalid closing statement `{@code }}`, which
balances the used braces in the `{@code ...}` fragments and combines
the first invalid statement with the last one.

Correct markup in Javadoc for unbalanced braces

---

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java
src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java

- Null guards in place to handle one or more nulls specified as one of the parameters of the method to invoke.
- Check for an exact match of the actual parameter types against all of the methods on the class. This prevents picking an "upcasted" method (i.e. int specified but a method with a double is chosen).
- Throw an IllegalStateException with a helpful message if multiple candidate methods were found. This happens when multiple Methods had the same "distance" from the desired parameter types. Before this change the algorithm would just chose the first one.
- Tests for the above.

[LANG-1544] MethodUtils.invokeMethod NullPointerException in case of null in args list

---

src/main/java/org/apache/commons/lang3/CharSequenceUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsEqualsIndexOfTest.java

Crash when the the char to be searched value it's out of range >=  '\u0000' <= '\uFFFF'
Getting the next error -->
`java.lang.IllegalArgumentException: Not a valid Unicode code point: 0xFFFFF936`
Basically the problem is that when it is verified that the character to search is less than MIN_SUPPLEMENTARY_CODE_POINT, the search is not exited of the loop. It continues searching but this time values less than or equal to Character.MAX_CODE_POIN

[LANG-1631] - Check if Character is defined

---

src/main/java/org/apache/commons/lang3/time/FastDatePrinter.java
src/test/java/org/apache/commons/lang3/time/FastDatePrinterTest.java

https://issues.apache.org/jira/browse/LANG-1637

[LANG-1637] Fix 2 digit week year formatting

---

src/main/java/org/apache/commons/lang3/text/StrLookup.java
src/main/java/org/apache/commons/lang3/text/StrMatcher.java
src/main/java/org/apache/commons/lang3/text/translate/AggregateTranslator.java

Fix broken Javadoc links to commons-text

---

pom.xml

Fixed test failures related to accessing private fields of ArrayList in ReflectionToStringBuilder while running ToStringBuilderTest in Java 16

LANG-1667: Allow tests to access java.util classes such as ArrayList in Java 16

---

src/main/java/org/apache/commons/lang3/time/FastDateParser.java

Fixed issue with parsing certain locales using day periods introduced in OpenJDK 16 and later resolved in OpenJDK 17

LANG-1669: OpenJDK 16 Day Period Parsing

---

src/main/java/org/apache/commons/lang3/math/NumberUtils.java

Updated documentation in NumberUtils to correctly state that a NullPointerException is thrown when the array is null, not an IllegalArgumentException.

LANG-1663: Update documentation to list correct exception for null array parameters

---

src/main/java/org/apache/commons/lang3/time/StopWatch.java

The descriptions for `formatTime()` and `formatSplitTime()` were reversed; the former said "Returns the split time" and the latter said "returns the time".
This PR switches their descriptions so that they now match the behavior of the methods.

Fixing reversed Javadoc descriptions in StopWatch

---

src/main/java/org/apache/commons/lang3/LocaleUtils.java

Use the HashSet collection for using the **contains()** method on the given Locale object.
The change improves the time complexity of this method from O(n) for ArrayList to O(1) for HashSet

Use Set instead of List for checking the contains() method

---

src/main/java/org/apache/commons/lang3/LocaleUtils.java
src/test/java/org/apache/commons/lang3/LocaleUtilsTest.java

This pull request is a partial fix for [LANG-1172](https://issues.apache.org/jira/browse/LANG-1172) adding support for dashes as delimiters for locales as per [BCP47](https://tools.ietf.org/html/bcp47#section-4) thus enabling parsing of locales such as `en-GB` in addition to the previously supported (but not to spec) `en_GB`.

LANG-1172: Support dash as a delimiter in locales

---

src/main/java/org/apache/commons/lang3/time/DateUtils.java
src/test/java/org/apache/commons/lang3/time/DateUtilsTest.java

Hello! This is another PR fixing inconsistent `NullPointerException`/`IllegalArgumentException` exception javadocs.
I added several new assertions on the tests when I noticed that they were missing.
While I was at it, I took the time to add some new documentation (and tests) on the range of methods such as `DateUtils.setMonth()`. I often misremember that months start with 0 and days start with 1.
```java
* @throws NullPointerException if the date is null
* @throws IllegalArgumentException if {@code amount} is not in the range
*  {@code 0 <= amount <= 11}
* @since 2.4
*/
public static Date setMonths(final Date date, final int amount) {
```
```java
final String outsideOfRangeAssertionMessage = "DateUtils.setMonths did not throw an expected IllegalArgumentException 
for amount outside of …
```

Fixing and adding DateUtils exception Javadocs

---

src/main/java/org/apache/commons/lang3/StringUtils.java

There're some redundant method calling and index checking in StringUtils.unwrap(String, String), which can be deleted to make unwrap(,) more concise and efficient.
Please refer to: https://issues.apache.org/jira/browse/LANG-1679 (a JMH test result also provided)

[LANG-1679] Improve performance of StringUtils.unwrap(String, String)

---

src/main/java/org/apache/commons/lang3/StringUtils.java

This PR replaces StringJoiner by StringBuilder in StringUtils.join methods. 
The change is limited to methods which use primitives as input only. 
Please find more details here: 
1. https://issues.apache.org/jira/browse/LANG-1675
2. https://github.com/apache/commons-lang/pull/784
JMH tests -  StringBuilder vs StringJoiner may be found in dedicated repository. Full logs, code and results included.
https://github.com/HubertWo/apache-commons-lang-jmh

LANG-1675 - Improve performance of StringUtils.join for primitives

---

.github/workflows/maven.yml

GitHub asks developers to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …

ci: Add GitHub token permissions for workflows

---

pom.xml
src/changes/changes.xml
src/conf/spotbugs-exclude-filter.xml

Reverts #896 as we can do a better job with the Spotbugs issues that are reported in the new release, instead of simply ignoring everything and bumping spotbugs.

Revert #896 spotbugs update

---

src/test/java/org/apache/commons/lang3/compare/ComparableUtilsTest.java

Static methods in ComparableUtils had 0 coverage this fixes that
Contributed on behalf of the @opencastsoftware open source team

Increase test coverage of ComparableUtils from 71% to 100%

---

src/test/java/org/apache/commons/lang3/builder/MultilineRecursiveToStringStyleTest.java

I noticed some of the array types (byte, float and short) weren't being tested, but when I added tests for them using the test class WithArrays it made several other tests fail, so I have also made changes which I hope will make it easier to add changes in the future.
Contributed on behalf of the @opencastsoftware open source team

Increase method test coverage of MultilineRecursiveToStringStyle

---

src/test/java/org/apache/commons/lang3/CharSequenceUtilsTest.java

Line 36 in CharSequenceUtils usually returns true for at least one test in a test run, but occasionally (for instance in PR 898) it doesn't. This is because the majority of the tests rely on randomly generated strings.
Contributed on behalf of the @opencastsoftware open source team

Fix unstable coverage of CharSequenceUtils tests noticed during merge of PRs 898 and 899

---

src/main/java/org/apache/commons/lang3/StringUtils.java

This MR fixes a typo with the StringUtils.upperCase(String str) javadoc
Updated #lowerCase to #upperCase in scenarios where Locale needs to be provided for case transformation

fix StringUtils.upperCase(String str) java doc

---

src/main/java/org/apache/commons/lang3/ClassUtils.java

method `toCanonicalName` use method  Validate.notNull  , so it could throw npe.
Meanswhile  `getClass`  use method `toCanonicalName` , so these method also throw npe. 
https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/ClassUtils.java#L559

Update ClassUtils Javadoc with some missing throws NPE

---

src/main/java/org/apache/commons/lang3/ObjectUtils.java
src/test/java/org/apache/commons/lang3/ObjectUtilsTest.java

* Original JIRA ticket (not by me): https://issues.apache.org/jira/projects/LANG/issues/LANG-1689
* Method `isEmpty` in `ObjectUtils` was modified to return the negation of `Optional.isPresent` (i.e. `!optional.isPresent()`) when the passed in object is an Optional.
* The object contained within the Optional is not checked if it is also empty. This gives the caller the option to check if it's present (or not) on their own.
* For instance, the caller might want to do something like the following:
`ObjectUtils.isEmpty(optional) && ObjectUtils.isNotEmpty(optional.get())`.

Lang 1689 add optional to objectutils isempty

---

src/main/java/org/apache/commons/lang3/time/DurationUtils.java
src/test/java/org/apache/commons/lang3/time/DurationUtilsTest.java

Same as [b16050](https://github.com/apache/commons-lang/pull/939/commits/b160500b936998ab11cce9e7e1159bf5d296cbc6) but without breaking compatibility.

Rename method and fix typo.

---

src/main/java/org/apache/commons/lang3/time/DateFormatUtils.java

Added documentation indicating that DateFormatUtils does not support week year format YYYY like in java.util.Calendar, and it will default to yyyy current year format.

LANG-1638: Added docs regarding week year support

---

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java
src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java

JIRA: [https://issues.apache.org/jira/browse/LANG-1694](https://issues.apache.org/jira/browse/LANG-1694)
MethodUtils.getMatchingMethod() fails with "Found multiple candidates for method" message if the method is **an override of an abstract method** and parameter types do not exactly match the declared types.
The behavior of this method has changed between versions 3.11 and 3.12.0. Previously, the method would pick the first method that matches the signature and replace it only if a method with a more specific signature is found. Maybe it's a compatibility issue.
Fix: Keep only one candidate to return directly, if there are more than two candidates, continue to compare whether the declaration classes of the first two methods are the same, if not, also consider the first method the best …

[LANG-1694] MethodUtils.getMatchingMethod() fails with "Found multiple candidates"

---

src/main/java/org/apache/commons/lang3/EnumUtils.java

Fixed a small typo in the EnumUtils documentation, where the wording does not match that of other methods in the class.

Typo in EnumUtils class

---

src/main/java/org/apache/commons/lang3/builder/EqualsBuilder.java

As pointed by LANG-1643, the `ArrayList<>()` constructor creates an empty List which will always grow at first add, which is done in the next line of code in `EqualsBuilder`

[LANG-1643] Construct ArrayList with better default size

---

src/test/java/org/apache/commons/lang3/ThreadUtilsTest.java

When running `testThreadGroups` and `testThreadGroupsById` in two threads, they have the same thread group name, will cause `testThreadGroups` test failed, such as `assertEquals(1, ThreadUtils.findThreadGroupsByName("thread_group_DDZZ99__").size());`->`expected: 1, actual: 2`.
[Junit5 writing-tests-parallel-execution-config](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config)
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.mode.classes.default=concurrent
```

ThreadUtilsTest#testThreadGroups will test failed when using Junit5 parallel test

---

src/main/java/org/apache/commons/lang3/SystemUtils.java

Fixes a typo in the `SystemUtils` class that assigned `JAVA_VENDOR` constant so it now calls `SystemProperties.getJavaVendor()`. Also updated the Javadoc comment.

LANG-1699: Corrected value of SystemUtils.JAVA_VENDOR

---

src/main/java/org/apache/commons/lang3/SystemUtils.java

This PR contains fixing macOS Big Sur detection, which started from version 11 and adds support for detecting macOS Monterey (12) and Ventura (13). Note that it might be beneficial to add `@since x.x` comment to the respective docs since I didn't know which version they're being included in.

SystemUtils.java: Fix and updates related to macOS

---

src/changes/changes.xml
src/main/java/org/apache/commons/lang3/time/DurationFormatUtils.java
src/test/java/org/apache/commons/lang3/time/DurationFormatUtilsTest.java

Relatively simple low-impact implementation of optional tokens within DurationFormatUtils. Useful when you need more human readable duration strings.
Brackets [] are used to denote optional tokens. Optional tokens are only printed if non-zero. Optional literals are only printed if the preceding non-literal was non-zero.
e.g. A single format:  `[d'd 'H'h 'm'm ']s's'`
Can produce outputs like:
```
1d 2h 3m 14s
2h 3m 14s
3m 14s
14s
0s
```
2 unit tests added.

Syntax for optional tokens in DurationFormatUtils

---

src/main/java/org/apache/commons/lang3/arch/Processor.java

This PR fixes an incorrect Javadoc description in `Processor` (introduced in 16d587d).

Fix Incorrect Javadoc Description in Processor

---

src/main/java/org/apache/commons/lang3/ClassUtils.java

I was reading the Javadoc [online](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/ClassUtils.html#getShortClassName-java.lang.Class-) and was confused by the reference, until I noticed that instead of pointing to itself, the idea is to point to `getShortClassName(String)`.

(doc) Point to right getShortClassName flavor in Javadoc for relevant notes

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsIsMixedCaseTest.java

The changes optimize the mixed-case detecting function in StringUtils.java by reducing redundant character property checks. The loop will now return early when both uppercase and lowercase are present, preventing further unnecessary operations. It also introduces a local variable to store the character being checked, reducing the number of method calls to get the character. The end return statement is also simplified to return false, as the true condition has already been covered inside the loop.

Improve performance of StringUtils.isMixedCase()

---

src/main/java/org/apache/commons/lang3/concurrent/ThresholdCircuitBreaker.java
src/test/java/org/apache/commons/lang3/concurrent/ThresholdCircuitBreakerTest.java

According to the document, checkState() should return `true` if the circuit breaker is currently closed。

Fix ThresholdCircuitBreaker

---

src/main/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/AtomicInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/BackgroundInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/ConstantInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializer.java
src/test/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/AtomicInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/ConstantInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerTest.java

This is associated with https://issues.apache.org/jira/browse/LANG-1716
See also discussion on #1119
------
This pull request adds a method `isInitialized()` to all implementations of ConcurrentInitializer. 
Here are the design decisions I made, and the rationales for them:
* Using `NO_INIT` for `AtomicInitializer` and `AtomicSafeInitializer`
* * Apart from making it easier to write an `isInitialized()` method this ensures that if `Atomic*Initializer` returns null it will correctly cache that behaviour as the docs say it should. This is a bug fix, but it may break backwards compatibility if someone inadvertently depends on the old behaviour. I chose to the correct thing now, and am drawing attention to it here to discuss if we actually want this fix.
* Including `isInitialized()` in …

Add method ConcurrentInitializer#isInitialized()

---

src/main/java/org/apache/commons/lang3/builder/AbstractSupplier.java
src/main/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/AtomicInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/BackgroundInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/CallableBackgroundInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/LazyInitializer.java
src/main/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializer.java
src/test/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializerCloseAndExceptionsTest.java
src/test/java/org/apache/commons/lang3/concurrent/AtomicInitializerSupplierTest.java
src/test/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializerSupplierTest.java
src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerSupplierTest.java
src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerTest.java
src/test/java/org/apache/commons/lang3/concurrent/LazyInitializerCloserTest.java
src/test/java/org/apache/commons/lang3/concurrent/LazyInitializerFailableCloserTest.java
src/test/java/org/apache/commons/lang3/concurrent/LazyInitializerSupplierTest.java
src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerSupplierTest.java
src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerTest.java

- Allow a Supplier for initialized object
- Allow a Consumer to close the managed object

Use LazyInitializer without subclassing.

---

src/main/java/org/apache/commons/lang3/ArchUtils.java
src/main/java/org/apache/commons/lang3/arch/Processor.java
src/test/java/org/apache/commons/lang3/ArchUtilsTest.java

Add RISC-V support to ArchUtils and its dependency class, Processor.

LANG-1717: support RISC-V in ArchUtils

---

src/main/java/org/apache/commons/lang3/ObjectUtils.java
src/main/java/org/apache/commons/lang3/concurrent/UncheckedExecutionException.java
src/main/java/org/apache/commons/lang3/concurrent/UncheckedTimeoutException.java
src/main/java/org/apache/commons/lang3/exception/UncheckedException.java
src/main/java/org/apache/commons/lang3/exception/UncheckedIllegalAccessException.java
src/main/java/org/apache/commons/lang3/exception/UncheckedInterruptedException.java
src/main/java/org/apache/commons/lang3/exception/UncheckedReflectiveOperationException.java
src/main/java/org/apache/commons/lang3/reflect/FieldUtils.java

This PR fixes Javadoc syntax errors where `@{code` were incorrectly used instead of `{@code`.

Fix Javadoc syntax errors

---

src/test/java/org/apache/commons/lang3/EnumUtilsTest.java

Found two non-deterministic tests failing in EnumUtilsTest.java 
Test names: [test_getEnumMap](https://github.com/apache/commons-lang/blob/912ab7154d5280a2632f375b5efd97e1b70149a4/src/test/java/org/apache/commons/lang3/EnumUtilsTest.java#L341), [test_getEnumMap_keyFunction](https://github.com/apache/commons-lang/blob/912ab7154d5280a2632f375b5efd97e1b70149a4/src/test/java/org/apache/commons/lang3/EnumUtilsTest.java#L355)
The issue we're encountering in the test arises from the nature of the Map collection in Java. The Map returned by the getEnumMap method does not guarantee the order of its elements. So, the test fails sometimes. 
https://github.com/apache/commons-lang/blob/912ab7154d5280a2632f375b5efd97e1b70149a4/src/test/java/org/apache/commons/lang3/EnumUtilsTest.java#L342
This is …

Fixed two non-deterministic tests in EnumUtilsTest.java

---

src/main/java/org/apache/commons/lang3/math/NumberUtils.java
src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java

`NumberUtils.createNumber(String)` method implements lots of number checks to ensure the provided string is indeed a number. But there is a wrong conditional checking in the code, that could result in unexpected StringIndexOutOfBoundsException if a specially crafted input is provided. This PR fixes the problem by changing the conditional check criterion.

LANG-1721: Fix wrong number check that cause StringIndexOutOfBoundsException

---

pom.xml

Back in 2019, there were issues with generating coverage reports with Jacoco v0.8.3 on JDK 13 (PR #433). Since then, Jacoco has been updated to v0.8.10, which officially supports JDK 19/20. Since coverage reports can now be generated with JDK 13+, it is proposed that this profile be removed as obsolete.
https://github.com/jacoco/jacoco/releases

Drop obsolete JDK 13 Maven profile

---

src/main/java/org/apache/commons/lang3/math/NumberUtils.java
src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java

This PR wraps possible `IndexOutOfBoundsException` with `NumberFormatException` when invalid string is parsed to `NumberUtils.getMantissa(String, int)` method and cause the String.substring(int, int) throws `IndexOutOfBoundsException`.

[LANG-1723]: Throw NumberFormatException instead of IndexOutOfBoundsException in NumberUtils.getMantissa(String, int)

---

RELEASE-NOTES.txt

Ref: #1130
Commons Lang 3.14.0 was released before #1130 got merged and the same error made its way into the release notes. Thus, this PR fixes the error reported in #1130, but in `RELEASE-NOTES.txt`.

Fix broken release notes

---

src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java

This passed locally so this bug might not be present any more, or perhaps it depends on JDK versions, or I don't understand it, or something. Let's see what the CI says and find out.

[LANG-1702] test for LANG-1702

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTrimStripTest.java

Changed normalizer form to NFKD.
See [Unicode Standard Annex 15](https://unicode.org/reports/tr15/)
This fixes the issue for the most part.
See additional tests in StringUtilsTrimStripTest.testStripAccents.
This does not appear to fix LANG-1655

StringUtils.stripAccents() should handle ligatures, UTF32 math blocks, etc.

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTrimStripTest.java

In Vietnamese, we have the characters "đ" and "Đ" (For reference, here is the Wikipedia page about this character: https://en.wikipedia.org/wiki/D_with_stroke.) When using your function, we need to manually replace these characters to remove their diacritical marks. It would be wonderful if you could add support for removing the diacritical marks from these two characters in your library. Thank you!

StringUtils.stripAccents(String) doesn't handle "\u0111" and "\u0110" (Vietnamese)

---

src/main/java/org/apache/commons/lang3/text/StrBuilder.java

Update StrBuilder.java to reflect changes made to commons-text with regards to newline. (https://github.com/apache/commons-text/commit/f934b1a539e483a54eeedd97394b5defde8254ea)

Same changes as [TEXT-234]

---

src/main/java/org/apache/commons/lang3/CachedRandomBits.java
src/main/java/org/apache/commons/lang3/RandomStringUtils.java
src/test/java/org/apache/commons/lang3/CachedRandomBitsTest.java

The previous implementation used  ThreadLocalRandom#current()

Reimplement RandomStringUtils on top of SecureRandom#getInstanceStrong()

---

src/main/java/org/apache/commons/lang3/AppendableJoiner.java
src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java
src/test/java/org/apache/commons/lang3/AppendableJoinerTest.java

Refactor string joining into AppendableJoiner
Joins an array or Iterable into an existing Appendable like a StringBuilder, aiming for call sites to avoid creating intermediary Strings. This is like `String.join(CharSequence, CharSequence)`, `String.join(CharSequence, Iterable)`, and `StringJoiner`.
Keep an instance in a (static) variable for efficient joining into an `Appendable` or `StringBuilder` without creating temporary Strings.
Use the builder and instance methods to reuse the same joining prefix, suffix, delimiter, and string conversion.
For example:
```java
// A reuseable instance
private static final AppendableJoiner<Object> JOINER = AppendableJoiner.builder()
.setPrefix("[")
.setSuffix("]")
.setDelimiter(", ")
.get();
...
// Builds straight into a StringBuilder:
StringBuilder …
```

Refactor string joining into AppendableJoiner

---

src/changes/changes.xml
src/main/java/org/apache/commons/lang3/RandomStringUtils.java
src/test/java/org/apache/commons/lang3/RandomStringUtilsTest.java
src/test/java/org/apache/commons/lang3/time/FastDateFormatTest.java

Fixes https://issues.apache.org/jira/browse/LANG-1745

[LANG-1745] RandomStringUtils.random() with a negative character index should throw IllegalArgumentException

---

src/main/java/org/apache/commons/lang3/time/StopWatch.java

Added a JavaDoc link from StopWatch to DurationUtils, as DurationUtils provide similar functiontionality, which could be used in simple use cases.

Add Javadoc links from StopWatch to DurationUtils

---

src/main/java/org/apache/commons/lang3/StringUtils.java

Add missing quotation marks in examples.

Fix Javadoc in StringUtils.splitPreserveAllTokens()

---

src/main/java/org/apache/commons/lang3/RandomStringUtils.java
src/test/java/org/apache/commons/lang3/RandomStringUtilsTest.java

An optimization introduced in commit f382d61a03778ccf838c6c051bd8692e4834dec2 incorrectly assumed that letters and numbers/digits are ASCII.
For example, `RandomStringUtils.random(1, 0x4e00, 0x4e01, true, false)` would take too long to terminate and would not output the correct answer, that is the string with a single character `0x4e00`. The issue is that `end` would be replaced by `'z' + 1 = 123` (the latest ASCII letter + 1) there: https://github.com/apache/commons-lang/blob/f382d61a03778ccf838c6c051bd8692e4834dec2/src/main/java/org/apache/commons/lang3/RandomStringUtils.java#L266-L270
Thus, we would have `end < start` and `gap = end - start < 0`.
This PR fixes this issue by restricting the optimization to cases where only ASCII characters are requested, that is `end < 0x7f`. This PR …

Fix handling of non-ASCII letters & numbers in RandomStringUtils

---

README.md

Ahoy @garydgregory, 👋
It appears that [https://maven-badges.herokuapp.com ](https://maven-badges.herokuapp.com/)is no longer functioning, resulting in a broken Maven Central badge in the README. I've noticed that other Apache projects (e.g., [maven-stage-plugin](https://github.com/apache/maven-stage-plugin/blob/master/README.md)) use [shields.io ](https://shields.io/badges/maven-central-version) as an alternative. If there are no plans to restore the maven-badges app, this is a trivial patch to fix it. If you find it appropriate, I can raise similar PRs for other repositories in the Apache group affected by this issue.

Fix broken URL to project location in Maven Central

---

src/main/java/org/apache/commons/lang3/StringUtils.java
src/test/java/org/apache/commons/lang3/StringUtilsTest.java

https://issues.apache.org/jira/browse/LANG-1753
The method `replaceEachRepeatedly` calls `replaceEach` repeatedly until no more replacements are possible or `timeToLive < 0`. The `timeToLive` starts with the value of `searchList.length`. The current implementation can't distinguish between infinite loops and deeply nested string patterns. In both cases, it continues replacements until it hits the time-to-live limit and throws `IllegalStateException` if replacements are still possible.
The problem with [LANG-1528](https://issues.apache.org/jira/browse/LANG-1528) fix is that in some cases, it allows partially replaced strings after TTL is exceeded. This fix reverts `replaceEach` logic back to version 3.10 (see PR #505), but allows deeper dives due to an increased initial TTL value. The …

[LANG-1753] StringUtils.replaceEachRepeatedly regression in 3.11+

---

src/main/java/org/apache/commons/lang3/Strings.java
src/test/java/org/apache/commons/lang3/StringsTest.java

https://issues.apache.org/jira/browse/LANG-1682
There have been several attempts ([PR #848](https://github.com/apache/commons-lang/pull/848), [PR #1040](https://github.com/apache/commons-lang/pull/1040)) to introduce the `startsWithAnyIgnoreCase` method to the already overcrowded `StringUtils` class. This discussion led to the creation of the `Strings` class (which supersedes `StringUtils`), providing similar functionality but managing case-sensitivity through:
- Case-sensitive (`Strings.CS`) instance
- Case-insensitive (`Strings.CI`) instance
In the recent [commit](https://github.com/apache/commons-lang/commit/479532b83db2d7b228e4128f2db02233f91e6e91), the `Strings` class now supports the requested `startsWithAny` functionality. This PR adds a test group to cover case-insensitive …

[LANG-1682] Javadoc and test: Use Strings.CI.startsWithAny method instead

---

src/main/java/org/apache/commons/lang3/text/WordUtils.java

Just minor change in coding style to make code clearer and easier to manage.
I didn't create a Jira issue since as per the documentation, it's a minor issue and not a bug or feature. I'm getting accustomed to this project.
P.S.
This is my first PR with this project, I did go through your documentations/guides; I'd appreciate a bit of patience in case I missed something or if I didn't follow a certain point instead of rejecting my PR outright and leaving me confused. Thank you

Removed the if-else and replaced with clearer data flow.

---

src/main/java/org/apache/commons/lang3/time/StopWatch.java

As the title says this PR reverts the deprecation of ``StopWatch#getTime`` to fix [LANG-1761](https://issues.apache.org/jira/browse/LANG-1761)
Checklist (removed irrelevant points):

LANG-1761 Revert deprecation of ``StopWatch#getTime``

---

src/main/java/org/apache/commons/lang3/StringUtils.java

Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:

Fix Javadoc typo and improve clarity in defaultIfBlank method

---

src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java

Remove an unnecessary reference to `java.lang.reflect.AnnotatedType`, which does not exist on Android. We immediately call `getType()` on it, so we might just as well use the method that gives us `Type[]` directly.

[LANG-1773] Apache Commons Lang no longer builds on Android

---

pom.xml
src/main/java/org/apache/commons/lang3/CachedRandomBits.java
src/main/java/org/apache/commons/lang3/RandomStringUtils.java
src/test/java/org/apache/commons/lang3/RandomStringUtilsTest.java

Added a length restriction to `RandomStringutils`, limiting the cache to 60M entries.  Because of rejections the bitIndex in the underling cache can overflow when right shifting.   Also added a test to verify the fix.
This test takes quite a while to run, so if necessary I can create a profile for slow tests to exclude the test from the normal build.

[LANG-1772] Restrict size of cache to prevent overflow errors

---

pom.xml
src/changes/changes.xml

This PR updates the `project.scm.url` field in the Maven POM to point to the GitHub repository URL (`https://github.com/apache/commons-lang`).
While this field is not used directly by Maven during builds, it is increasingly leveraged by tools like *Dependabot* to:
* Associate the Maven artifact with its GitHub repository
* Automatically include release notes, changelogs, and commit history in pull requests for new versions
By using the GitHub URL, we improve the quality and completeness of metadata shown in automated upgrade PRs and make it easier for users to trace changes between releases.

[LANG-1776] Use GitHub URL in `project.scm.url`

---

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java
src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java

fix https://issues.apache.org/jira/browse/LANG-1778

LANG-1778 fix by reversing order

---

pom.xml

fix indentation and remove unnecessary whitespace
This pull request improves the formatting of `pom.xml` by fixing inconsistent indentation and removing unnecessary whitespace.  
No functional changes were made.  
This helps maintain clarity and consistency for contributors working with the build configuration.

Clean up pom.xml formatting

---

src/main/java/org/apache/commons/lang3/StringUtils.java

Removed the extra space in - 1 when handling null str2, changing it to -1 for consistent syntax.

Remove extra whitespace in string comparison logic

---

src/main/java/org/apache/commons/lang3/ClassUtils.java
src/test/java/org/apache/commons/lang3/ClassUtilsTest.java

This PR improves handling of invalid class name inputs to `ClassUtils.getShortCanonicalName(String name)`
- Added checks for the invalid class names, and replaced `RuntimeException `with descriptive `IllegalArgumentException`.
- Added tests for invalid input scenarios and confirmed all existing and new test cases pass with `mvn`.

[LANG-1774] Improve handling of ClassUtils.getShortCanonicalName for invalid input data

---

src/main/java/org/apache/commons/lang3/EnumUtils.java
src/main/java/org/apache/commons/lang3/compare/ObjectToStringComparator.java

Fix isEnum() Method Logic:
Correct the method to return true only when enumClass is not null and is actually an enum class
Change implementation to: return enumClass != null && enumClass.isEnum();
Update getFirstEnum() Method:
Invert the condition check to properly handle valid enum classes
Should proceed with stream operations only when isEnum(enumClass) returns true

Fix internal inverted logic in private isEnum() method and correct its usage in getFirstEnum()
