src/main/java/org/apache/commons/lang3/builder/ToStringStyle.java, src/test/java/org/apache/commons/lang3/builder/JsonToStringStyleTest.java
except number, boolean, Array and nested object structures, other types like char, String, Date etc. in java should be `appendAsString`.
add method `appendDetail(StringBuffer buffer, String fieldName, char value)` to `JsonToStringStyle`
modify `appendDetail(StringBuffer buffer, String fieldName, Object value)`
=> fix JsonToStringStyle

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
New pull request created, was originally https://github.com/apache/commons-lang/pull/38
=> LANG-701 - Added new joinWith method to support varargs

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java
Fixes issue https://issues.apache.org/jira/browse/LANG-1122 as discussed.
I also added a link to an article on my blog about shift algorithm, as it was discussed previously. Hope it's fine, if not, I can remove it.
=> Fix issue 1122

src/main/java/org/apache/commons/lang3/StringUtils.java, src/main/java/org/apache/commons/lang3/text/WordUtils.java, src/test/java/org/apache/commons/lang3/text/WordUtilsTest.java
Checks if the String contains all words.
```java
StringUtils.containsAllWords("lorem ipsum dolor sit amet", "ipsum", "lorem", "dolor") == true
StringUtils.containsAllWords("lorem ipsum dolor sit amet", "ipsum", null, "lorem", "dolor") == false
StringUtils.containsAllWords("ab", "b") == false
```
=> LANG-1135 - Add method containsAllWords to WordUtils

src/main/java/org/apache/commons/lang3/event/EventListenerSupport.java, src/test/java/org/apache/commons/lang3/event/EventListenerSupportTest.java
Added new addListener() method that takes a boolean for if duplicates are allowed.
Added test method to make sure that duplicate listeners are not added.
=> Added new addListener method that allows checking for duplicate listeners.

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsEqualsIndexOfTest.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
Add null safe methods in `StringUtils` to compare 2 Strings :
```java
public static int compare(final String str1, final String str2);
public static int compare(final String str1, final String str2, final boolean nullIsLess);
public static int compareIgnoreCase(final String str1, final String str2);
public static int compareIgnoreCase(final String str1, final String str2, final boolean nullIsLess);
```
Those methods are null safe equivalent to :
```java
str1.compareTo(str2);
str1.compareToIgnoreCase(str2);
```
=> LANG-1171 Add null safe compare methods in StringUtils :

src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
- as is
```
* @param outputStatics
*            whether to include transient fields
```
- to be
```
* @param outputStatics
*            whether to include static fields
```
=> Fix ReflectionToStringBuilder toString javadoc

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
=> LANG-787: Add StringUtils#removeIgnoreCase

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java, src/test/java/org/apache/commons/lang3/concurrent/BasicThreadFactoryTest.java
There are some obvious typos in non-critical parts of project like comments and JavaDoc.
=> Fix typos in comments and javadoc.

src/test/java/org/apache/commons/lang3/concurrent/CircuitBreakingExceptionTest.java, src/test/java/org/apache/commons/lang3/concurrent/ConcurrentUtilsTest.java, src/test/java/org/apache/commons/lang3/exception/AbstractExceptionTest.java, src/test/java/org/apache/commons/lang3/exception/CloneFailedExceptionTest.java
- add AbstractExceptionTest
- add CircuitBreakingExceptionTest
- add CloneFailedExceptionTest
- cover specific test cases
=> Improve test covarage

src/test/java/org/apache/commons/lang3/CharRangeTest.java, src/test/java/org/apache/commons/lang3/RandomUtilsTest.java, src/test/java/org/apache/commons/lang3/StringEscapeUtilsTest.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
CharRangeTest 98% -> 100%
RandomUtilsTest 90% -> 100%
StringEscapeUtilsTest 95% -> 100%
StringUtilsTest -> 99% (a few more lines covered)
=> Increase test coverage

.travis.yml, checkstyle.xml, pom.xml, src/changes/changes.xml, src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/main/java/org/apache/commons/lang3/CharSequenceUtils.java, src/main/java/org/apache/commons/lang3/StringUtils.java, src/main/java/org/apache/commons/lang3/concurrent/Computable.java, src/main/java/org/apache/commons/lang3/concurrent/annotation/package-info.java, src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java, src/main/java/org/apache/commons/lang3/time/DateUtils.java, src/test/java/org/apache/commons/lang3/ClassUtilsTest.java, src/test/java/org/apache/commons/lang3/StringUtilsEmptyBlankTest.java, src/test/java/org/apache/commons/lang3/StringUtilsEqualsIndexOfTest.java, src/test/java/org/apache/commons/lang3/exception/AbstractExceptionContextTest.java
@chtompki 
I'm tackling the root cause now.
=> LANG-1300: Change CharSequenceUtils to support supplementary characters

src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java
Adding test cases to test the following methods of "ToStringBuilder" class. With this, the code coverage stands at 100%.
1) append(final String fieldName, final boolean[] array)
2) append(final String fieldName, final boolean[] array, final boolean fullDetail)
3) append(final String fieldName, final byte[] array)
4) append(final String fieldName, final byte[] array, final boolean fullDetail)
5) append(final String fieldName, final char[] array)
6) append(final String fieldName, final char[] array, final boolean fullDetail)
7) append(final String fieldName, final double[] array)
8) append(final String fieldName, final double[] array, final boolean fullDetail)
9) append(final String fieldName, final float[] array)
10) append(final String fieldName, final float[] array, final boolean …
=> LANG-1325: Increase test coverage of ToStringBuilder class to 100%

src/main/java/org/apache/commons/lang3/StringUtils.java
Fixed faulty samples of isNoneEmpty/isNoneBlank and also added new ones to isAnyEmpty/isNoneEmpty/isAnyBlank/isNoneBlank for better understanding
=> docs - fixed faulty samples of isNoneEmpty/isNoneBlank

src/test/java/org/apache/commons/lang3/event/EventUtilsTest.java
Clean up the `EventUtilsTest` class in order to make it easier to read and maintain,
=> Clean up EventUtilsTest

src/main/java/org/apache/commons/lang3/StringUtils.java
=> LANG-1375: defaultString(str) reuses defaultString(str, defaultStr)

pom.xml
Just a tiny change to show everybody I'm still alive :o)
=> Update maven-pmd-plugin to latest version

.travis.yml, pom.xml, src/changes/changes.xml, src/test/java/org/apache/commons/lang3/SystemUtilsTest.java
This PR only updates the build. I've not scanned through the code to find stuff that can be deprecated. This is still on my list.
=> LANG-1415: Update Java Language requirement to 1.8

pom.xml, src/test/java/org/apache/commons/lang3/ValidateTest.java
- Add dependencies required for JUnit 5
- Update one test (ValidateTest) to use the JUnit 5 test API
=> LANG-1416: Update to JUnit 5

src/main/java/org/apache/commons/lang3/Functions.java, src/test/java/org/apache/commons/lang3/FunctionsTest.java
Fix the CI issues (rat, Checkstyle, javadoc) in `Functions` and `FunctionsTest`.
=> Fix CI issues in Functions and FunctionsTest

src/main/java/org/apache/commons/lang3/StringUtils.java
wrapIfMissing function was referencing warp function in the javadoc
=> Fix javadoc in wrapIfMissing

src/main/java/org/apache/commons/lang3/ClassUtils.java, src/main/java/org/apache/commons/lang3/concurrent/LazyInitializer.java
Fixing couple of dangling javadocs, converted to comments.
=> (doc) Fixing couple of dangling javadocs, converted to comments.

src/main/java/org/apache/commons/lang3/text/ExtendedMessageFormat.java
Switch statement with only 2 branches seems unnecessary unless future additions are planned. If not, converting to if/else seems clearer.
=> Changing switch statement to if/else statement for greater clarity

src/main/java/org/apache/commons/lang3/StringUtils.java
Revise the java-doc of splitPreserveAllTokens(final String str, final String separatorChars, final int max)
=> revise java-doc error

src/main/java/org/apache/commons/lang3/RandomUtils.java, src/test/java/org/apache/commons/lang3/RandomUtilsTest.java
=> RandomUtils : comment error

src/changes/changes.xml, src/main/java/org/apache/commons/lang3/builder/DiffBuilder.java, src/main/java/org/apache/commons/lang3/builder/DiffResult.java, src/main/java/org/apache/commons/lang3/builder/Diffable.java, src/main/java/org/apache/commons/lang3/builder/ReflectionDiffBuilder.java, src/test/java/org/apache/commons/lang3/builder/DiffBuilderTest.java
[LANG-1486] Generify builder classes Diffable, DiffBuilder, and DiffResult.
=> [LANG-1486] Generify builder classes Diffable, DiffBuilder, and

src/main/java/org/apache/commons/lang3/ClassLoaderUtils.java, src/test/java/org/apache/commons/lang3/ClassLoaderUtilsTest.java
[LANG-1487] Add ClassLoaderUtils with toString() implementations for URLClassLoader.
=> [LANG-1487] Add ClassLoaderUtils with toString() implementations.

src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java
Add more test inputs for ArrayUtils.toMap() method as follow:
- zero-length array
- all null values array
- duplicate keys in array
=> Add more test inputs for ArrayUtils.toMap() method

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java
Based of the opened issue. Tests for indexesOf were also added.
=> [LANG-1177] Added indexesOf methods and simplified removeAllOccurences

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
added handling of abbrevMarker being an empty string
=> Lang 1463: StringUtils abbreviate returns String of length greater than maxWidth

src/main/java/org/apache/commons/lang3/ComparableUtils.java, src/test/java/org/apache/commons/lang3/ComparableUtilsTest.java
I have turned `feeAmount.compareTo(BigDecimal.ZERO) > 0` into `is(feeAmount).greaterThan(BigDecimal.ZERO)` and decided to share.
=> Add ComparableUtils

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java, src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java, src/test/java/org/apache/commons/lang3/reflect/testbed/GenericParent.java, src/test/java/org/apache/commons/lang3/reflect/testbed/StringParameterizedChild.java
https://issues.apache.org/jira/browse/LANG-1518
=> [LANG-1518] MethodUtils.getAnnotation() with searchSupers = true does not work if super is generic

src/main/java/org/apache/commons/lang3/math/NumberUtils.java
See [JIRA issue LANG-1527](https://issues.apache.org/jira/projects/LANG/issues/LANG-1527).
=> LANG-1527: Remove an redundant argument check in NumberUtils

src/main/java/org/apache/commons/lang3/StringUtils.java
I saw typo in the line I'm interested in, so just fixed it.
=> Fix Javdoc for StringUtils.appendIfMissingIgnoreCase()

src/main/java/org/apache/commons/lang3/CharSequenceUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
=> [LANG-1545] CharSequenceUtils.regionMatches is wrong dealing with Georgian.

src/test/java/org/apache/commons/lang3/StreamsTest.java
update tests to use assertThrows and check in parallel instead of in serial
=> StreamsTest junit-jupiter

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/main/java/org/apache/commons/lang3/Conversion.java, src/main/java/org/apache/commons/lang3/text/StrBuilder.java, src/main/java/org/apache/commons/lang3/time/FastDatePrinter.java
Hi.
I see you use Math.max and min in this repo's some places but in other places use `:?`
So should we use Math.max and min in all places like these?
Or, should we convert all Math.max/min back to `:?` ?
=> [LANG-1562] use Math.max and min

src/main/java/org/apache/commons/lang3/SystemUtils.java, src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java, src/test/java/org/apache/commons/lang3/StringEscapeUtilsTest.java, src/test/java/org/apache/commons/lang3/time/DateUtilsRoundingTest.java
=> [LANG-1560] Refine Javadoc

src/main/java/org/apache/commons/lang3/StringUtils.java, src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java, src/main/java/org/apache/commons/lang3/reflect/ConstructorUtils.java, src/main/java/org/apache/commons/lang3/text/StrBuilder.java, src/main/java/org/apache/commons/lang3/text/StrMatcher.java, src/main/java/org/apache/commons/lang3/text/StrTokenizer.java, src/test/java/org/apache/commons/lang3/builder/CompareToBuilderTest.java, src/test/java/org/apache/commons/lang3/builder/EqualsBuilderTest.java, src/test/java/org/apache/commons/lang3/text/StrTokenizerTest.java
change array style from `int a[]` to `int[] a`
=> [LANG-1553] Change array style from `int a[]` to `int[] a`

src/test/java/org/apache/commons/lang3/text/ExtendedMessageFormatTest.java
change from addAll to constructors for some List.
=> [LANG-1552] Change from addAll to constructors for some List

src/main/java/org/apache/commons/lang3/ClassLoaderUtils.java, src/main/java/org/apache/commons/lang3/Locks.java, src/main/java/org/apache/commons/lang3/reflect/MemberUtils.java, src/main/java/org/apache/commons/lang3/time/DateUtils.java, src/test/java/org/apache/commons/lang3/EnumUtilsTest.java, src/test/java/org/apache/commons/lang3/event/EventUtilsTest.java, src/test/java/org/apache/commons/lang3/text/ExtendedMessageFormatTest.java, src/test/java/org/apache/commons/lang3/time/FastDateParserTest.java
=> [LANG-1554] Fix typos

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
I fixed this simple bug, I'd like to collaborate on it, I'm ready to consider any suggestions
=> [LANG-1528] StringUtils.replaceEachRepeatedly gives IllegalStateException

src/test/java/org/apache/commons/lang3/FunctionsTest.java
There is a trailing space in one class who blocks the checkstyle.
(Which might caused by my pr so I come here to fix it.)
Sorry about that.
=> fix checkstyle.

pom.xml
by changing defaultGoal in pom.xml
=> Add binary compatibility check to Maven default goal

src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java, src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java
https://issues.apache.org/jira/browse/LANG-1618
=> [LANG-1618] - TypeUtils. containsTypeVariables does not support GenericArrayType

src/main/java/org/apache/commons/lang3/StringUtils.java
reduce calling charAt several times.
also change order to try to reduce function calls.
=> [LANG-1584] Refine StringUtils.isNumericSpace

src/main/java/org/apache/commons/lang3/StringUtils.java
don't create more empty String.
=> [LANG-1580] refine StringUtils.deleteWhitespace

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/main/java/org/apache/commons/lang3/time/FastDateFormat.java, src/main/java/org/apache/commons/lang3/time/FastDateParser.java, src/main/java/org/apache/commons/lang3/time/FormatCache.java
1) Found Javadoc examples in ArrayUtils.addFirst() incorrectly refer to add() at 9 places.
2) Basic code format in 3 files from time package.
=> [LANG-1626] Correction in Javadoc of some methods.

src/main/java/org/apache/commons/lang3/StringUtils.java, src/test/java/org/apache/commons/lang3/StringUtilsTest.java
Join Implementation it's missing for primitive of type boolean
https://issues.apache.org/jira/browse/LANG-1636
=> [LANG-1636] - Boolean Join Function

src/main/java/org/apache/commons/lang3/text/translate/UnicodeUnpairedSurrogateRemover.java, src/main/java/org/apache/commons/lang3/time/FastDateParser.java
* Add final variable.try to make the code read-only
* inline Variable. Simplify code
=> Minor Improvements

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/main/java/org/apache/commons/lang3/ClassUtils.java, src/main/java/org/apache/commons/lang3/RandomStringUtils.java, src/main/java/org/apache/commons/lang3/StringUtils.java, src/main/java/org/apache/commons/lang3/builder/DiffBuilder.java, src/main/java/org/apache/commons/lang3/concurrent/BackgroundInitializer.java, src/main/java/org/apache/commons/lang3/concurrent/EventCountCircuitBreaker.java, src/main/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializer.java, src/main/java/org/apache/commons/lang3/math/Fraction.java, src/main/java/org/apache/commons/lang3/math/NumberUtils.java, src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java, src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java, src/main/java/org/apache/commons/lang3/text/translate/NumericEntityUnescaper.java, src/main/java/org/apache/commons/lang3/time/FastDateParser.java, src/main/java/org/apache/commons/lang3/time/FormatCache.java
* Add final variable.try to make the code read-only
=> Minor Improvement: Add final variable.try to make the code read-only

src/main/java/org/apache/commons/lang3/builder/EqualsBuilder.java, src/main/java/org/apache/commons/lang3/builder/HashCodeBuilder.java, src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java, src/main/java/org/apache/commons/lang3/builder/ToStringStyle.java, src/main/java/org/apache/commons/lang3/math/Fraction.java, src/main/java/org/apache/commons/lang3/text/StrSubstitutor.java, src/main/java/org/apache/commons/lang3/text/StrTokenizer.java
* Remove redundant initializer
=> Minor Improvement: Remove redundant initializer

src/main/java/org/apache/commons/lang3/BooleanUtils.java
create true && false Yes && No On && Off  String constant in order to re use variable, and make the code more readable
=> true & false String constant

pom.xml, src/site/resources/checkstyle/checkstyle.xml
https://issues.apache.org/jira/browse/COMMONSSITE-145
=> [COMMONSSITE-145] upgrade checkstyle

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java
Adds a mention of IllegalStateException in case no unique method is found.
=> LANG-1668 Update getMatchingMethod documentation.

src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java, src/main/java/org/apache/commons/lang3/text/StrBuilder.java, src/main/java/org/apache/commons/lang3/time/DateUtils.java
* Inline var
* Simplify conditions
* Make final variable
=> Minor changes

src/main/java/org/apache/commons/lang3/time/DateUtils.java, src/main/java/org/apache/commons/lang3/time/FastDateParser.java, src/main/java/org/apache/commons/lang3/time/FastDatePrinter.java, src/test/java/org/apache/commons/lang3/time/DateUtilsTest.java, src/test/java/org/apache/commons/lang3/time/FastDateFormatTest.java, src/test/java/org/apache/commons/lang3/time/FastDatePrinterTest.java
Contributed on behalf of the @opencastsoftware open source team
=> LANG-1680 Add support for standalone month formats

src/main/java/org/apache/commons/lang3/time/CalendarUtils.java, src/test/java/org/apache/commons/lang3/time/CalendarUtilsTest.java
Add method to gets the current day of year given a calendar.
=>  Add gets the current day of year.

src/main/java/org/apache/commons/lang3/StringUtils.java
Added empty string example for `isMixedCase` method. Junit test for this example is already present in `StringUtilsTest.java`
=> Added empty string example for isMixedCase method.

src/main/java/org/apache/commons/lang3/StringUtils.java
added example for space in `indexOfIgnoreCase`
=> Add example for space in StringUtils#indexOfIgnoreCase()

src/main/java/org/apache/commons/lang3/ArrayUtils.java, src/main/java/org/apache/commons/lang3/Range.java, src/main/java/org/apache/commons/lang3/builder/ToStringBuilder.java, src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java, src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java, src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java, src/test/java/org/apache/commons/lang3/time/DurationUtilsTest.java
Hello! I added some missing javadoc for null arguments and wrote tests when they didn't exist.
I tried to keep the diffs as small as possible and the sentences consistent.
I will be happy to change anything if needed. Thanks.
=> Add missing exception javadoc/tests for some null arguments

src/main/java/org/apache/commons/lang3/math/NumberUtils.java
Fixing typos when found during work with NumberUtils.java
=> (doc) Fix typos in Javadoc

src/test/java/org/apache/commons/lang3/ArrayUtilsTest.java, src/test/java/org/apache/commons/lang3/exception/AbstractExceptionContextTest.java
`assertEquals(int expected, int actual)`
=> Swap the order of assertion args (first excepted then actual)

src/main/java/org/apache/commons/lang3/ArrayUtils.java
updated the JavaDoc for the insert methods in ArrayUtils to say the methods return also null if the input array is null
=> Update Javadoc for the insert methods in ArrayUtils

src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java, src/test/java/org/apache/commons/lang3/exception/ExceptionUtilsTest.java
--corrected the isUnchecked method to check for null
--created test for null case
=> LANG-1647-correction-of-isUnchecked-method

src/main/java/org/apache/commons/lang3/ArrayUtils.java
Avoid using reserved word `class`, so `clss`. 
`clazz` is better? :)
=> Refactor rename the variable name from 'clss' to 'clazz'

src/main/java/org/apache/commons/lang3/time/package-info.java
Putting release notes in Javadoc goes out of date fast
@garydgregory
=> Remove 2.1 specific comment

src/test/java/org/apache/commons/lang3/RandomStringUtilsTest.java
Discussion: https://lists.apache.org/thread/xr5d3r1hvvn42vlzqnk70hhwx5xgvm06
=> Update critical value for chi-square test

src/main/java/org/apache/commons/lang3/concurrent/BackgroundInitializer.java, src/main/java/org/apache/commons/lang3/concurrent/LazyInitializer.java, src/test/java/org/apache/commons/lang3/ArrayUtilsSetTest.java, src/test/java/org/apache/commons/lang3/ValidateTest.java, src/test/java/org/apache/commons/lang3/builder/ReflectionDiffBuilderTest.java, src/test/java/org/apache/commons/lang3/builder/ToStringBuilderTest.java, src/test/java/org/apache/commons/lang3/concurrent/AbstractConcurrentInitializerCloseAndExceptionsTest.java, src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerSupplierTest.java, src/test/java/org/apache/commons/lang3/concurrent/BackgroundInitializerTest.java, src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerSupplierTest.java, src/test/java/org/apache/commons/lang3/concurrent/MultiBackgroundInitializerTest.java, src/test/java/org/apache/commons/lang3/function/MethodInvokersFailableBiFunctionTest.java, src/test/java/org/apache/commons/lang3/reflect/MethodUtilsTest.java, src/test/java/org/apache/commons/lang3/reflect/TypeUtilsTest.java, src/test/java/org/apache/commons/lang3/util/FluentBitSetTest.java
All changes are limited to the javadoc / test scope.
=> Minor grammar fixes

src/main/java/org/apache/commons/lang3/Conversion.java, src/test/java/org/apache/commons/lang3/builder/ConversionTest.java
The Conversion class seems to have gotten committed with no tests. This PR adds a few, though by no means full coverage. @garydgregory
=> Test the Conversion class

src/test/java/org/apache/commons/lang3/AbstractLangTest.java
=> inline method

src/main/java/org/apache/commons/lang3/event/EventListenerSupport.java, src/test/java/org/apache/commons/lang3/event/EventListenerSupportTest.java
Allow EventListenerSupport to handle (and ignore) exception from listeners allowing invocation of all listeners
This is an alternative to https://github.com/apache/commons-lang/pull/1156
=> Allow EventListenerSupport to handle (and ignore) exception from listeners allowing invocation of all listeners

src/main/java/org/apache/commons/lang3/StringEscapeUtils.java
=> remove TODO from deprecated class we're not going to refactor

src/main/java/org/apache/commons/lang3/util/FluentBitSet.java
=> [LANG-1735] Fix Javadoc for FluentBitSet.setInclusive(int, int)

src/main/java/org/apache/commons/lang3/RuntimeEnvironment.java, src/test/java/org/apache/commons/lang3/RuntimeEnvironmentTest.java
Adds RuntimeEnv.inContainer() to check whether we are running in a container.
Tests for Docker, Podman. Also WSL but not as a container.
=> Add RuntimeEnvironment.inContainer()

src/main/java/org/apache/commons/lang3/RandomStringUtils.java, src/main/java/org/apache/commons/lang3/RandomUtils.java, src/test/java/org/apache/commons/lang3/RandomStringUtilsTest.java, src/test/java/org/apache/commons/lang3/RandomUtilsTest.java, src/test/java/org/apache/commons/lang3/time/FastDateFormatTest.java
Refactor `RandomUtils` and `RandomStringUtils` with `secure()` and `insecure()`
instances.
For example:
```java
RandomStringUtils.secure().randomInt();
RandomStringUtils.insecure().randomInt();
```
=> Feature/randomutils secure() and insecure()

src/main/java/org/apache/commons/lang3/builder/DiffBuilder.java, src/main/java/org/apache/commons/lang3/builder/ReflectionDiffBuilder.java
After trying to run the code examples in `DiffBuilder` and `ReflectionDiffBuilder`, there were a few things to clean up.
=> Correct Javadoc code example

src/main/java/org/apache/commons/lang3/Strings.java
Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:
=> Strings::equalsAny: CI doc string should show it's insensitive

src/main/java/org/apache/commons/lang3/Strings.java
Updated several javadoc which is referencing old method names in new Strings-API
Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:
=> LANG-1780: updated Strings javadoc

src/main/java/org/apache/commons/lang3/StringUtils.java
The wrong Javadoc pointed to Strings.CI where this is a case sensitive operation.
Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:
=> [javadoc] Fix @deprecated link for StringUtils#startsWithAny
